this_file := $(lastword $(MAKEFILE_LIST))

objs := BufferAllocation_1.o NetworkInterface.o phyHandling.o
confs :=
dirs :=
softlink_froms :=
EXTRA_CFLAGS_SELF :=
EXTRA_CFLAGS_DOWN +=

include $(obj_mk)
