this_file := $(lastword $(MAKEFILE_LIST))

target := libcmsis.a

objs := startup_stm32h743xx.o system_stm32h7xx.o
confs :=
dirs :=
softlink_froms :=
EXTRA_CFLAGS_SELF :=
EXTRA_CFLAGS_DOWN +=

include $(target_mk)
